version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'swc*'
      - dependency-name: 'v8*'
      - dependency-name: 'sourcemap*'
      - dependency-name: 'bincode*'
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
